# Generated by Django 4.2.7 on 2024-04-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=12, null=True)),
                ('pic', models.ImageField(blank=True, default='pro_pic/avatar_2.png', null=True, upload_to='pro_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beautify.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ShopProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=12)),
                ('pic', models.ImageField(default='shop_pic/shop.jpg', upload_to='shop_pic')),
                ('activity', models.CharField(choices=[('Available', 'Available'), ('Offline', 'Offline')], default='Offline', max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('preferredGender', models.CharField(choices=[('Unisex', 'Unisex'), ('Men', 'Men'), ('Women', 'Women')], max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautify.categorymodel')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beautify.shopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviwed_shop', to='beautify.shopprofilemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviwed_user', to='beautify.userprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='Pending', max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_shop', to='beautify.shopprofilemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_user', to='beautify.userprofilemodel')),
            ],
        ),
    ]
