# Generated by Django 4.2.7 on 2025-02-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautify', '0003_alter_shopprofilemodel_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofilemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
